<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-4K2IFQ7" failures="0" tests="4" name="tests.CreateUserTest" time="0.902" errors="1" timestamp="2024-02-29T18:45:00 IST" skipped="3">
  <testcase classname="tests.CreateUserTest" name="createUser" time="0.000">
    <skipped/>
  </testcase> <!-- createUser -->
  <testcase classname="tests.CreateUserTest" name="setup" time="0.902">
    <error message="please pass the correct envname:: qa" type="frameworkexception.FrameworkException">
      <![CDATA[frameworkexception.FrameworkException: please pass the correct envname:: qa
at configuration.ConfigurationManager.initProp(ConfigurationManager.java:44)
at base.BaseTest.setup(BaseTest.java:32)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:340)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:294)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:623)
at org.testng.TestRunner.beforeRun(TestRunner.java:613)
at org.testng.TestRunner.run(TestRunner.java:584)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:41)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:443)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:67)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </error>
  </testcase> <!-- setup -->
  <testcase classname="tests.CreateUserTest" name="createUser" time="0.000">
    <skipped/>
  </testcase> <!-- createUser -->
  <testcase classname="tests.CreateUserTest" name="createUser" time="0.000">
    <skipped/>
  </testcase> <!-- createUser -->
</testsuite> <!-- tests.CreateUserTest -->
